FROM node:24-alpine3.21 AS builder
WORKDIR /kv-server

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run lint

FROM node:24-alpine3.21 AS runtime
WORKDIR /kv-server

COPY package*.json ./
RUN npm install --production

COPY --from=builder /kv-server .

EXPOSE 4000

CMD [ "node", "index.js" ]
